version: '3'
services:
  rabbit:
    image: rabbitmq:management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge
